### PR TITLE
[TASK] Remove de.* after joining Crowdin Project

### PR DESCRIPTION
**Pull request by prathers**
Since you've added the extension to the Crowdin project, you should avoid keeping translation files inside the project. If you want an instance to get files, you should use the translation update inside TYPO3 Install Tools

### CODE REVIEW

**Comment by froemken** [comment]
Hello @prathers 

maps2 still supports TYPO3 9.5 where CrowdIn is deactivated by default in feature toggle. So I can remove these files first while removing TYPO3 9 compatibility.
Please give me a note, if I'm wrong.

Stefan

**Comment by prathers** [comment]
If the extension is not on the old Pootle server, you're right.

**Comment by froemken** [comment]
Jep, maps2 is currently not on the Pootle Server:

https://translation.typo3.org/projects/TYPO3.ext.maps2/

So what should I do with this PR? Should I keep it 1,5 years until TYPO3 11 release?

**Comment by froemken** [comment]
Good morning @prathers 

I have removed TYPO3 9 compatibility. With this change I already have removed the de files.

Thank you for your help

Stefan

**Pull request closed without merging**
